#!/usr/bin/env bash

#Consider creating specialized git repositories as follows.

workingDir="$PWD"

export netName=default
mkdir -p "$workingDir"/"$netName"
cd "$workingDir"/"$netName"

git init
git add .
git commit -a -m "first commit"

mkdir _lib

git submodule add git@github.com:mirage335/CoreAutoSSH.git ./_lib/coreautossh
git submodule add --force git@github.com:mirage335/Ubiquitous_Bash.git ./_lib/ubiquitous_bash

git submodule update --init --recursive

#cp -a ./_lib/coreautossh/_local ./
mkdir -p ./_local/ssh
cp -d --preserve=all ./_lib/ubiquitous_bash/_lib/ssh/ops ./_local/ssh/ops

cp -a ./_lib/coreautossh/_prog ./
cp -a ./_lib/coreautossh/_config ./

cp -d --preserve=all ./_lib/coreautossh/cautossh ./
cp -d --preserve=all ./_lib/coreautossh/compile ./

cp -d --preserve=all ./_lib/coreautossh/README.md ./
cp -d --preserve=all ./_lib/coreautossh/USAGE.html ./
cp -d --preserve=all ./_lib/coreautossh/TiddlySaver.jar ./

cp -d --preserve=all ./_lib/coreautossh/update ./
cp -d --preserve=all ./_lib/coreautossh/fork ./


./compile
