#!/usr/bin/env bash

#Consider creating specialized git repositories as follows.

workingDir="$PWD"

export netName=default
mkdir -p "$workingDir"/"$netName"
cd "$workingDir"/"$netName"

mkdir ./_lib
mkdir ./_prog

git init

git submodule add --depth 1 git@github.com:mirage335/CoreAutoSSH.git ./_lib/coreautossh

#Parent derivative of ubiquitous_bash.
git submodule update --depth 1 --init ./_lib/coreautossh/_lib/ubiquitous_bash

#git submodule update --depth 1 --init --recursive

cp ./_lib/coreautossh/cautossh ./
cp ./_lib/coreautossh/compile.sh ./
cp ./_lib/coreautossh/README.md ./
cp ./_lib/coreautossh/USAGE.html ./
cp ./_lib/coreautossh/TiddlySaver.jar ./

##### Hardcoded Configuration
mkdir -p ./_config
cp -a ./_lib/coreautossh/_lib/ubiquitous_bash/_config/. ./_config

##### Parent Derivative Scripts
mkdir -p ./_prog
cp -a ./_lib/coreautossh/_prog/. ./_prog

##### Runtime Configuration
mkdir -p ./_local/ssh

#Parent derivative of ubiquitous_bash.
cp ./_lib/coreautossh/_lib/ubiquitous_bash/_lib/ssh/ops ./_local/ssh/ops

#cp -a ./_lib/coreautossh/_local ./

##### Specialized project scripts.
cp ./_lib/coreautossh/update ./
cp ./_lib/coreautossh/fork ./


./compile.sh

git add .
git commit -a -m "first commit"
