#!/usr/bin/env bash

#Critical prerequsites.
_getAbsolute_criticalDep() {
	! type realpath > /dev/null 2>&1 && return 1
	! type readlink > /dev/null 2>&1 && return 1
	! type dirname > /dev/null 2>&1 && return 1
	
	#Known issue on Mac. See https://github.com/mirage335/ubiquitous_bash/issues/1 .
	! realpath -L . > /dev/null 2>&1 && return 1
	
	return 0
}
! _getAbsolute_criticalDep && exit 1

! type basename > /dev/null 2>&1 && exit 1

#Retrieves absolute path of current script, while maintaining symlinks, even when "./" would translate with "readlink -f" into something disregarding symlinked components in $PWD.
#However, will dereference symlinks IF the script location itself is a symlink. This is to allow symlinking to scripts to function normally.
#Suitable for allowing scripts to find other scripts they depend on. May look like an ugly hack, but it has proven reliable over the years.
_getScriptAbsoluteLocation() {
	local absoluteLocation
	if [[ (-e $PWD\/$0) && ($0 != "") ]] && [[ "$1" != "/"* ]]
			then
	absoluteLocation="$PWD"\/"$0"
	absoluteLocation=$(realpath -L -s "$absoluteLocation")
			else
	absoluteLocation=$(realpath -L "$0")
	fi

	if [[ -h "$absoluteLocation" ]]
			then
	absoluteLocation=$(readlink -f "$absoluteLocation")
	absoluteLocation=$(realpath -L "$absoluteLocation")
	fi
	echo $absoluteLocation
}
alias getScriptAbsoluteLocation=_getScriptAbsoluteLocation

#Retrieves absolute path of current script, while maintaining symlinks, even when "./" would translate with "readlink -f" into something disregarding symlinked components in $PWD.
#Suitable for allowing scripts to find other scripts they depend on.
_getScriptAbsoluteFolder() {
	dirname "$(_getScriptAbsoluteLocation)"
}
alias getScriptAbsoluteFolder=_getScriptAbsoluteFolder

#Retrieves absolute path of parameter, while maintaining symlinks, even when "./" would translate with "readlink -f" into something disregarding symlinked components in $PWD.
#Suitable for finding absolute paths, when it is desirable not to interfere with symlink specified folder structure.
_getAbsoluteLocation() {
	if [[ "$1" == "" ]]
	then
		echo
		return
	fi
	
	local absoluteLocation
	if [[ (-e $PWD\/$1) && ($1 != "") ]] && [[ "$1" != "/"* ]]
			then
	absoluteLocation="$PWD"\/"$1"
	absoluteLocation=$(realpath -L -s "$absoluteLocation")
			else
	absoluteLocation=$(realpath -L "$1")
	fi
	echo $absoluteLocation
}
alias getAbsoluteLocation=_getAbsoluteLocation

#Retrieves absolute path of parameter, while maintaining symlinks, even when "./" would translate with "readlink -f" into something disregarding symlinked components in $PWD.
#Suitable for finding absolute paths, when it is desirable not to interfere with symlink specified folder structure.
_getAbsoluteFolder() {
	local absoluteLocation=$(_getAbsoluteLocation "$1")
	dirname "$absoluteLocation"
}
alias getAbsoluteLocation=_getAbsoluteLocation

export scriptLocation="$(_getScriptAbsoluteFolder)"

_upgrade_ub() {
	cd "$scriptLocation"
	if [[ -e "$scriptLocation"/_lib/ubiquitous_bash ]]
	then
		cd "$scriptLocation"/_lib/ubiquitous_bash
		git pull
	fi
}

_upgrade_coreautossh() {
	! [[ -e "$scriptLocation"/_lib/coreautossh ]] && return 1
	
	cd "$scriptLocation"/_lib/coreautossh
	git pull
	git submodule update
}

_upgrade_derive() {
	! [[ -e "$scriptLocation"/_lib/coreautossh ]] && return 1
	
	cd "$scriptLocation"
	cp -a ./_lib/coreautossh/_prog ./

	#cp -d --preserve=all ./_lib/coreautossh/cautossh ./
	cp -d --preserve=all ./_lib/coreautossh/compile.sh ./

	cp -d --preserve=all ./_lib/coreautossh/upgrade ./
}

_upgrade_cautossh() {
	cd "$scriptLocation"
	if ! git diff-index --quiet HEAD --
	then
		echo 'CONFLICT'
		exit 1
	fi
	git pull

	_upgrade_ub "$@"

	_upgrade_coreautossh "$@"

	_upgrade_derive "$@"

	./compile.sh
}

_upgrade_cautossh "$@"


